BEGIN;

CREATE SCHEMA IF NOT EXISTS beta_stage;

CREATE TABLE IF NOT EXISTS beta_stage.companies (
  company_id text PRIMARY KEY,
  company_name text NOT NULL,
  website text,
  headquarter_country text,
  owned_by_subsidiary_of text,
  status text,
  public_stock_ticker text,
  address text,
  founding_year integer,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.company_roles (
  role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id text NOT NULL REFERENCES beta_stage.companies(company_id) ON DELETE CASCADE,
  category text NOT NULL,
  company_name text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.company_locations (
  location_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id text NOT NULL REFERENCES beta_stage.companies(company_id) ON DELETE CASCADE,
  alternate_id text,
  company_name text,
  alternate_name text,
  location_type text,
  address text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.employee_counts (
  count_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id text NOT NULL REFERENCES beta_stage.companies(company_id) ON DELETE CASCADE,
  count_type text,
  employees integer,
  date_updated date,
  source text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.system_material_details (
  detail_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id text NOT NULL REFERENCES beta_stage.companies(company_id) ON DELETE CASCADE,
  process text,
  material_format text,
  material_type text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.service_provider_machines (
  machine_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id text NOT NULL REFERENCES beta_stage.companies(company_id) ON DELETE CASCADE,
  printer_manufacturer text,
  printer_model text,
  process text,
  material_type text,
  number_of_printers integer,
  count_type text,
  source text,
  update_year integer,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.service_pricing_quotes (
  quote_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id text REFERENCES beta_stage.companies(company_id) ON DELETE SET NULL,
  company_name text,
  material_category text,
  material text,
  process text,
  volume_cm3 numeric,
  manufacturing_cost numeric,
  shipping_cost numeric,
  day_ordered date,
  delivery_date date,
  lead_time_days integer,
  comments text,
  data_source text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.material_pricing_observations (
  observation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_date date,
  material text,
  material_class text,
  material_subclass text,
  company_id text REFERENCES beta_stage.companies(company_id) ON DELETE SET NULL,
  company_name text,
  form text,
  size text,
  process text,
  quantity_kg numeric,
  price_usd_per_kg numeric,
  source text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.company_revenue_facts (
  fact_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id text REFERENCES beta_stage.companies(company_id) ON DELETE SET NULL,
  company_name text,
  financial_metric text,
  metric_type text,
  revenue_native_currency numeric,
  native_currency text,
  revenue_usd numeric,
  estimate_actual text,
  period text,
  source text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.currency_conversion_rates (
  currency_code text NOT NULL,
  year integer NOT NULL,
  rate_to_usd numeric NOT NULL,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (currency_code, year)
);

CREATE TABLE IF NOT EXISTS beta_stage.company_contacts (
  contact_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name text NOT NULL,
  contact_name text,
  email text,
  interaction text,
  year_of_last_interaction integer,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.system_sales (
  sale_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_date date,
  year integer,
  company_name text,
  systems text,
  period_cumulative text,
  units numeric,
  measure text,
  source text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.mergers_acquisitions (
  event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text,
  published_at timestamptz,
  deal_date date,
  acquired_company text,
  acquiring_company text,
  acquired_company_id text REFERENCES beta_stage.companies(company_id) ON DELETE SET NULL,
  acquiring_company_id text REFERENCES beta_stage.companies(company_id) ON DELETE SET NULL,
  deal_size text,
  details text,
  additional_financial_info text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS beta_stage.trade_records (
  trade_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year integer,
  period text,
  product_code text,
  product_description text,
  reporter_name text,
  partner_name text,
  trade_flow_type text,
  value numeric,
  source text,
  created_at timestamptz DEFAULT now()
);

COMMIT;
